# Generated by Django 2.1.1 on 2018-10-13 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_guardianinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinfo',
            name='guardian',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.GuardianInfo'),
        ),
    ]
